#!/bin/bash
# Output:
# %env.IsBuildFailed%

export PATH="$PATH:/Library/Frameworks/Mono.framework/Versions/Current/Commands"
xbuild %teamcity.build.checkoutDir%/%env.iOSPath% /p:Configuration=Release /p:Platform=iPhone
buildResult=$?
if [[ $buildResult = '0' ]]
then
    echo 'Build success'
else
    echo 'Build failed'
echo "##teamcity[setParameter name='env.IsBuildFailed' value='true']"
fi