#!/bin/bash
# Output:
# %env.IsBuildFailed%
# %env.SkipRelease%: skip release process

# skip any action if true
if [[ %env.SkipRelease% = 'true' ]]
then
	echo 'No release tag found, skip step'
    exit 0
fi

export PATH="$PATH:/Library/Frameworks/Mono.framework/Versions/Current/Commands"
msbuild /t:SignAndroidPackage /p:Configuration=Release %teamcity.build.checkoutDir%/%env.DroidPath% /p:AndroidSdkDirectory=/Users/mac/sdk /p:AndroidNdkDirectory=/Users/mac/ndk
buildResult=$?
if [[ $buildResult = '0' ]]
then
    echo 'Build success'
else
    echo 'Build failed'
    echo "##teamcity[setParameter name='env.IsBuildFailed' value='true']"
fi