#!/bin/bash
# Input:
# %env.SonarQubeProjectName% : project name in SonarQube
# %env.SonarQubeToken% : sonarqube token for api calls
# %env.SonarQubeUrl% : url path for sonarqube
# %env.AppVersion%: new app version name

# skip any action if true
if [[ %env.SkipRelease% = 'true' ]]
then
	echo 'No release tag found, skip step'
    exit 0
fi

mono /Users/mac/Library/TeamCity/buildAgent/tools/scanner-msbuild/bin/SonarScanner.MSBuild.exe begin /k:"%env.SonarQubeProjectName%" /d:sonar.host.url="%env.SonarQubeUrl%" /d:sonar.login="%env.SonarQubeToken%" /v:"%env.AppVersion%"