#!/bin/bash
# Input: 
# %env.SkipTesting% : skip build/jira actions when needed											|| false
# Output:
# %env.IsBuildFailed%

# skip any action if true
if [[ %env.SkipTesting% = 'true' ]]
then
    exit 0
fi

export PATH="$PATH:/Library/Frameworks/Mono.framework/Versions/Current/Commands"
msbuild /t:SignAndroidPackage /p:Configuration=Release %teamcity.build.checkoutDir%/%env.DroidPath% /p:AndroidSdkDirectory=/Users/mac/sdk /p:AndroidNdkDirectory=/Users/mac/ndk
buildResult=$?
if [[ $buildResult = '0' ]]
then
    echo 'Build success'
else
    echo 'Build failed'
    echo "##teamcity[setParameter name='env.IsBuildFailed' value='true']"
fi