#!/bin/bash
# Input: 
# %env.SkipTesting% : skip build/jira actions when needed											|| false
# Output:
# %env.IsBuildFailed%
# %env.iOSPath% : path to iOS project

# skip any action if true
if [[ %env.SkipTesting% = 'true' ]]
then
    exit 0
fi

export PATH="$PATH:/Library/Frameworks/Mono.framework/Versions/Current/Commands"
xbuild %teamcity.build.checkoutDir%/%env.iOSPath% /p:Configuration=Release /p:Platform=iPhone
buildResult=$?
if [[ $buildResult = '0' ]]
then
    echo 'Build success'
else
    echo 'Build failed'
echo "##teamcity[setParameter name='env.IsBuildFailed' value='true']"
fi